version: 2
jobs:
  build:
    docker:
      - image: fmidev/rpmbuild:el7
        entrypoint: bash
        environment:
          RPM_BUILD_NCPUS: 2
    steps:
      - checkout
      - run:
          name: Create local repo
          command: createrepo /home/rpmbuild/rpmbuild/RPMS/x86_64
      - run:
          name: Install dependencies
          command: sudo yum-builddep --disableexcludes=smartmet-open -y *.spec 
      - run:
          name: make rpm
          command: |
            tar zcvf $HOME/rpmbuild/SOURCES/$CIRCLE_PROJECT_REPONAME.tar.gz --exclude-vcs $HOME/project
            rpmbuild -ba --define "_smp_mflags -j$RPM_BUILD_NCPUS" *.spec
      - run:
          name: Move artifacts
          command: sudo cp -av /home/rpmbuild/rpmbuild/RPMS /
      - store_artifacts:
          path: /RPMS
