version: 2.1
jobs:
  test-rhel8:
    docker:
      - image: fmidev/smartmet-cibase-8:latest
    resource_class: xlarge
    steps:
      - checkout
      - run:
          name: Check
          command: ls -l; ls -l /home/rpmbuild/project
      - run:
          name: Installation test
          command:
             ci-build dummy ;
             sudo yum install -y 'smartmet-plugin-wfs*' ;
             sudo yum -y upgrade 'smartmet-*' ;
      - run:
          name: Test prepare
          command: ci-build testprep
      - run:
          name: Test
          command: ci-build test
  test-rhel9:
    docker:
      - image: fmidev/smartmet-cibase-9:latest
    resource_class: xlarge
    steps:
      - checkout
      - run:
          name: Installation test
          command: ci-build dummy ; sudo yum install -y 'smartmet-plugin-wfs*'
      - run:
          name: Test prepare
          command: ci-build testprep
      - run:
          name: Test
          command: ci-build test
workflows:
  version: 2.1
  build-test:
    jobs:
      - test-rhel8
      - test-rhel9
